import type { Metadata, Viewport } from "next";
import {
  Geist,
  Geist_Mono,
  Noto_Sans_JP,
  Noto_Sans_KR,
  Noto_Serif,
} from "next/font/google";
import { SessionProvider } from "@/components/providers/session-provider";
import { KeyboardInsetSync } from "@/components/pwa/keyboard-inset-sync";
import { ServiceWorkerRegister } from "@/components/pwa/service-worker-register";
import { SplashScreen } from "@/components/pwa/splash-screen";
import { getCurrentAppSession } from "@/lib/session";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// CJK body fonts — match the design handoff's Korean/Japanese weight (incl. 900/black).
// Geist has no CJK glyphs, so Hangul/Kana previously fell back to a system font with
// no true black weight. preload:false keeps these large fonts off the critical path.
const notoSansKr = Noto_Sans_KR({
  variable: "--font-noto-kr",
  weight: ["400", "500", "700", "800", "900"],
  preload: false,
});

const notoSansJp = Noto_Sans_JP({
  variable: "--font-noto-jp",
  weight: ["400", "500", "700", "800", "900"],
  preload: false,
});

// Wordmark font — serif italic used for the "Stay Ops" brand mark across all shells.
const notoSerif = Noto_Serif({
  variable: "--font-wordmark",
  subsets: ["latin"],
  weight: ["600", "700"],
  style: ["italic", "normal"],
});

export const metadata: Metadata = {
  title: "StayOps",
  description: "Hotel operations app for field staff and office teams.",
  manifest: "/manifest.webmanifest",
  // iOS ignores the manifest icons for the home-screen icon — it needs apple-touch-icon.
  // Without these the installed app showed a blank/screenshot glyph.
  icons: {
    shortcut: "/favicon.ico",
    icon: [
      { url: "/favicon.ico", type: "image/x-icon" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "StayOps",
  },
};

// viewportFit: "cover" makes the app go edge-to-edge so safe-area-inset-* env()
// values are non-zero on notched devices (the mobile shell pads the top notch and
// bottom home-indicator with them). themeColor tints the browser top chrome /
// address bar the warm ivory so it blends with the app instead of a grey band.
// Both light/dark map to the SAME ivory: iOS Safari ignores a single themeColor in
// dark mode and falls back to black system chrome, so declaring an explicit dark
// variant (identical ivory) forces the light design's chrome in both schemes.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  // color-scheme: "light" tells iOS Safari to render the page canvas with light-mode
  // defaults even when the device is in OS dark mode. Without it, Safari falls back to
  // dark chrome/canvas (status bar + URL toolbar turn black) regardless of themeColor —
  // most visible when the sidebar scrim is up and Safari samples the dimmed content.
  colorScheme: "light",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f7f4ee" },
    { media: "(prefers-color-scheme: dark)", color: "#f7f4ee" },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getCurrentAppSession();

  return (
    <html
      lang={session?.user.preferredLanguage ?? "ko"}
      className={`${geistSans.variable} ${geistMono.variable} ${notoSansKr.variable} ${notoSansJp.variable} ${notoSerif.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      {/* iOS PWA native splash images — one per device resolution.
          Without these, iOS shows a blank white screen before the WebView paints.
          Generated by scripts/gen-splash.mjs; re-run when the icon changes. */}
      <head>
        <link rel="apple-touch-startup-image" media="(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/splash/apple-splash-1320-2868.png" />
        <link rel="apple-touch-startup-image" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/splash/apple-splash-1290-2796.png" />
        <link rel="apple-touch-startup-image" media="(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/splash/apple-splash-1206-2622.png" />
        <link rel="apple-touch-startup-image" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/splash/apple-splash-1179-2556.png" />
        <link rel="apple-touch-startup-image" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/splash/apple-splash-1284-2778.png" />
        <link rel="apple-touch-startup-image" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/splash/apple-splash-1170-2532.png" />
        <link rel="apple-touch-startup-image" media="(device-width: 360px) and (device-height: 780px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="/splash/apple-splash-1080-2340.png" />
        <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="/splash/apple-splash-750-1334.png" />
      </head>
      <body className="flex min-h-full flex-col">
        <SplashScreen />
        <ServiceWorkerRegister />
        <KeyboardInsetSync />
        <SessionProvider initialSession={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
