-- Attendance — atomic QR issuance / reissuance (Step 2).
-- See docs/product/21-attendance-payroll-workflow.md and
-- docs/engineering/11-attendance-payroll-technical-design.md.
--
-- Product rule: a site has exactly ONE active QR token at a time; reissuing deactivates the previous
-- token and links it to its successor (audit chain). Doing this as separate app statements risks
-- momentarily having two active tokens for one site (which the partial unique index
-- `attendance_qr_tokens_one_active_per_site_idx` would reject) or losing the replaced-by link on a
-- failure. This function performs deactivate → insert → link in a SINGLE transaction (a plpgsql body
-- is atomic), so the "one active token per site" guarantee always holds and the chain stays intact.
--
-- Authorization (owner-only) is enforced by the caller (the future web-dashboard server action, or the
-- dev temp-QR tool's dev guard) BEFORE this is called; this function only performs the write and is
-- granted to service_role only. The token string is generated by the caller and passed in.

create or replace function public.issue_attendance_qr(
  p_org uuid,
  p_site uuid,
  p_created_by uuid,
  p_token text
)
returns public.attendance_qr_tokens
language plpgsql
security definer
set search_path = public
as $$
declare
  old_id uuid;
  new_row public.attendance_qr_tokens;
begin
  -- Deactivate the current active token for this site (if any), capturing its id.
  update public.attendance_qr_tokens
    set is_active = false,
        revoked_at = now()
  where site_id = p_site
    and organization_id = p_org
    and is_active
  returning id into old_id;

  -- Insert the new active token. With the previous one already deactivated, the partial unique index
  -- (one active per site) is satisfied.
  insert into public.attendance_qr_tokens (organization_id, site_id, token, is_active, created_by_user_id)
  values (p_org, p_site, p_token, true, p_created_by)
  returning * into new_row;

  -- Link the replaced token to its successor for the audit chain.
  if old_id is not null then
    update public.attendance_qr_tokens
      set replaced_by_token_id = new_row.id
    where id = old_id;
  end if;

  return new_row;
end;
$$;

grant execute on function public.issue_attendance_qr(uuid, uuid, uuid, text) to service_role;
