import { describe, expect, it } from "vitest";
import { isRecurringOccurrenceDate } from "../tasks-recurrence";

describe("isRecurringOccurrenceDate", () => {
  it("accepts a date generated by a standard recurrence rule", () => {
    expect(isRecurringOccurrenceDate("weekly", "2026-08-03", "2026-08-10")).toBe(true);
  });

  it("rejects a date that does not belong to the recurrence", () => {
    expect(isRecurringOccurrenceDate("weekly", "2026-08-03", "2026-08-11")).toBe(false);
  });

  it("rejects dates before the recurrence anchor", () => {
    expect(isRecurringOccurrenceDate("daily", "2026-08-03", "2026-08-02")).toBe(false);
  });

  it("accepts a generated custom-weekday occurrence", () => {
    expect(isRecurringOccurrenceDate("custom:1,3,5", "2026-08-03", "2026-08-07")).toBe(true);
  });

  it("rejects malformed dates and unsupported recurrence rules", () => {
    expect(isRecurringOccurrenceDate("daily", "2026-08-03", "2026-8-4")).toBe(false);
    expect(isRecurringOccurrenceDate("custom", "2026-08-03", "2026-08-04")).toBe(false);
    expect(isRecurringOccurrenceDate(null, "2026-08-03", "2026-08-04")).toBe(false);
  });
});
